### ISSUE TITLE
Case sensitivity on import statements

### ISSUE THREAD

**Issue by furkansimsekli** [edtaskin/Pong#3]
Great work!

I tried to run Pong in my Linux system, but since you imported the modules without according to case sensitivity, it raises errors. I was able to fix it by changing import statements from `import ball`, `from constants import *` etc. to `import Ball`, `from Constants import *`.

I guess you are using Windows, and as far as I know that Python in Windows is case insensitive.

If you assign me, I can happily push my work so that Pong work in both operation system.

**Comment by edtaskin** [comment]
Hey Furkan, thank you! 
A while ago I changed the class names to fit Python conventions but didn't realize that the import statements were left in lower, like you said. Good catch!
